version: '3'
services:
  "web-app":
    build: "./web-app"
    ports:
      - "3000:8080"
      - "9229:9229"
    volumes:
      - "./web-app/src:/web-app/src"
    depends_on:
      - database
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=myDB
  session-database:
    build: session-database
    ports:
      - "6379:6379"
  spa:
    build: "./spa"
    ports:
      - "8080:3000"
    volumes:
      - "./spa:/spa"